apiVersion: v1
kind: Service
metadata:
  name: stolon-proxy-service
  namespace: mobility-asia
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: stolon-proxy
    stolon-cluster: kube-stolon

