apiVersion: v1  
kind: ServiceAccount  
metadata:  
  name: stolon-serviceaccount  
  namespace: mobility-asia

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: stolon
  namespace: mobility-asia
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default 
  namespace: mobility-asia

