apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-stolon-pv0
  namespace: mobility-asia
  labels: 
    storage-pv: postgresql-stolon-pv0
spec:
  capacity:
    storage: 1Gi  
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: mobilityasia
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-stolon-keeper-0
  namespace: mobility-asia
spec:
  accessModes:
  - ReadWriteMany
  selector: 
    matchLabels:
      storage-pv: postgresql-stolon-pv0
  resources:
     requests:
       storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-stolon-pv1
  namespace: mobility-asia
  labels: 
    storage-pv: postgresql-stolon-pv1
spec:
  capacity:
    storage: 1Gi  
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: mobilityasia-1
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-stolon-keeper-1
  namespace: mobility-asia
spec:
  accessModes:
  - ReadWriteMany
  selector: 
    matchLabels:
      storage-pv: postgresql-stolon-pv1
  resources:
     requests:
       storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-stolon-pv2
  namespace: mobility-asia
  labels: 
    storage-pv: postgresql-stolon-pv2
spec:
  capacity:
    storage: 1Gi  
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: mobilityasia-2
    readOnly: false
  persistentVolumeReclaimPolicy: Retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-stolon-keeper-2
  namespace: mobility-asia
spec:
  accessModes:
  - ReadWriteMany
  selector: 
    matchLabels:
      storage-pv: postgresql-stolon-pv2
  resources:
     requests:
       storage: 1Gi
